const ugandaDistricts = [
    "Abim",
    "Adjumani",
    "Agago",
    "Alebtong",
    "Amolatar",
    "Amudat",
    "Amuria",
    "Amuru",
    "Apac",
    "Arua",
    "Budaka",
    "Bududa",
    "Bugiri",
    "Buhweju",
    "Buikwe",
    "Bukedea",
    "Bukomansimbi",
    "Bukwo",
    "Bulambuli",
    "Buliisa",
    "Bundibugyo",
    "Bunyangabu",
    "Bushenyi",
    "Busia",
    "Butaleja",
    "Butambala",
    "Buvuma",
    "Buyende",
    "Dokolo",
    "Gomba",
    "Gulu",
    "Hoima",
    "Ibanda",
    "Iganga",
    "Isingiro",
    "Jinja",
    "Kaabong",
    "Kabale",
    "Kabarole",
    "Kaberamaido",
    "Kalangala",
    "Kaliro",
    "Kampala",
    "Kamuli",
    "Kamwenge",
    "Kanungu",
    "Kapchorwa",
    "Kasese",
    "Katakwi",
    "Kayunga",
    "Kibaale",
    "Kiboga",
    "Kibuku",
    "Kiruhura",
    "Kiryandongo",
    "Kisoro",
    "Kitgum",
    "Koboko",
    "Kole",
    "Kotido",
    "Kumi",
    "Kween",
    "Kyankwanzi",
    "Kyegegwa",
    "Kyenjojo",
    "Lamwo",
    "Lira",
    "Luuka",
    "Luwero",
    "Lwengo",
    "Lyantonde",
    "Manafwa",
    "Maracha",
    "Masaka",
    "Masindi",
    "Mayuge",
    "Mbale",
    "Mbarara",
    "Mitooma",
    "Mityana",
    "Mokono",
    "Moroto",
    "Moyo",
    "Mpigi",
    "Mubende",
    "Mukono",
    "Nakapiripirit",
    "Nakaseke",
    "Nakasongola",
    "Namayingo",
    "Namutumba",
    "Napak",
    "Nebbi",
    "Ngora",
    "Ntoroko",
    "Ntungamo",
    "Nwoya",
    "Otuke",
    "Oyam",
    "Pader",
    "Pallisa",
    "Rakai",
    "Rubirizi",
    "Rukungiri",
    "Sembabule",
    "Serere",
    "Sheema",
    "Sironko",
    "Soroti",
    "Tororo",
    "Wakiso",
    "Yumbe",
    "Zombo",
];


const signsAndSymptoms = [
    "Fever (≥38°C)",
    "Headache",
    "General Weakness",
    "Skin/Body Rash",
    "Sore Throat",
    "Vomiting",
    "Bleeding",
    "Abdominal Pain",
    "Aching Muscles/Pain",
    "Difficulty Swallowing",
    "Difficulty Breathing",
    "Lethargy/Weakness",
];


const alertSource = [
    {
        name: "Community Member",
    },
    { name: "VHT (Village Health Team)" },
    { name: "Health Facility" },
    { name: "Health Worker" },
    { name: "Schools" },
    { name: "Mass Gathering" },
    { name: "Point Of Entry" }
]


const alertResponse = [
    { name: "Infectious Disease(Communicable Diseases)" },
    { name: "Mass Gathering(CHAN,NRM Gathering)" },
    { name: "Disasters" },
    { name: "Routine Emergency" },
    { name: "NCD(Non Communicable Diseases)" },
    { name: "Other" },
]

const alertStatus = [
    { name: "Alive" },
    { name: "Dead" },
    { name: "Unknown" },
]

const alertActions = [
    { name: "Alert reported" },
    { name: "Alert verified" },
    { name: "Alert investigated" },
    { name: "Alert resolved" },
]

export {
    ugandaDistricts,
    signsAndSymptoms,
    alertSource,
    alertResponse,
    alertStatus,
    alertActions
}
